### ISSUE TITLE
cross library dependency

### ISSUE THREAD

**Issue by xambroz** [libyal/libuna#3]
Hello, 
there seems to be round dependency (chicken & egg) problem. The libuna depends on libcfile and libcfile depends on libuna. Please would it be possible to either separate the dependency or bind it to one?

Thank you
Michal Ambroz

**Comment by xambroz** [comment]
Actually same issue with the libcsystem

**Comment by ryandesign** [comment]
We've been asked to add libuna and your dozens of other libraries to MacPorts. MacPorts understandably does not support circular dependencies. Is there any guidance documented anywhere for packagers, explaining which library should have precedence in these circular dependency situations? Should we, for example, provide a libuna that depends on libcsystem, or a libcsystem that depends on libuna?

**Comment by xambroz** [comment]
Solution is probably to compile libuna separately (depends only on the libcstring and libcerror) , then compile the libcfile and libcsystem and then unatools (depends on libcfile/libcsystem).
It would be probably more transparent to separate code for the lib from the tool.

**Comment by joachimmetz** [comment]
So there is no need to make separate packages of all these libraries, some of them are just utility libraries that are separate projects for ease of maintenance. Why do you want to package and distribute them all separately?

As for the unatools, they are just small tools largely to test the library.

**Comment by ryandesign** [comment]
Ports for each of your libraries were submitted to MacPorts; I'm now working through them and noticing these problems. Which of your libraries would you suggest should not be packaged in a package manager like MacPorts?

**Comment by joachimmetz** [comment]
I opt to package what you really need, are you trying to package plaso or dfvfs?
Stick with the dependencies for those projects.

A word of caution some of the libraries are marked as [experimental](https://github.com/libyal/libyal/wiki) for a good reason. 

For context if you look at https://github.com/libyal/libyal/wiki/Overview:

I opt to stick with packaging:
- Data formats (only libfwsi if you want to provide the Python bindings)
- File formats
- In-file formats (libwrc only)
- File system formats
- Volume (system) formats
- Storage media image formats
- Utility libraries (libbfio only if you really have to)

Typically no need to package:
- Cross-platform functionality
- Data formats
- In-file formats
- Non-library projects
- Knowledge base projects

**Comment by ryandesign** [comment]
Yes, plaso and grr were submitted to MacPorts, with all these various libraries as dependencies submitted as separate ports. Yes, some of them are experimental versions. If you suggest we should not package experimental versions, then I guess we cannot offer plaso or grr in MacPorts until you make stable versions of their dependencies?

I don't know your libraries. I don't know what's required, what's optional, what's recommended. I only know what was submitted to MacPorts (here are [some of them](https://trac.macports.org/query?summary=~libyal)), and the problems I'm having processing those submissions.

**Comment by joachimmetz** [comment]
I see so a third party requested these to be added. Don't know their reason for submitting them all but they definitely have not spoken with me about it.

(Note still work in progress) What we have packaged for Ubuntu for the upcoming plaso release: https://launchpad.net/~gift/+archive/ubuntu/stable. I would stick with the libraries provided in the "Release" and "Bleeding Edge" tracks. The former for packaged plaso releases the latter for development.

>  If you suggest we should not package experimental versions

The word of caution here is largely you'll have to make sure the experimental versions keep up to date,.

I opt not to package the experimental version of libewf you'll find the last stable here: 
https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/ (or via Downloads link on the libewf wiki pages).

**Comment by joachimmetz** [comment]
Or [here](https://github.com/log2timeline/l2tbinaries/tree/master/macosx) for Mac OS X

**Comment by ryandesign** [comment]
I don't know whether ports for all your libraries have been submitted, just lots of them, presumably for the reason that he thought they were required for the software he ultimately wanted to use.

The ports I've already added to MacPorts in the past couple days, after cleaning up the submissions, are libcdata libcdatetime libcfile libclocale libcnotify libcthreads. I don't see any of those in your list of Ubuntu packages above. Are these libraries not required for anything? Should I remove them again?

**Comment by joachimmetz** [comment]
> Are these libraries not required for anything? Should I remove them again?

Not as stand-alone shared libraries. I opt to use them as static libraries included in the build of other libraries for now.

**Comment by joachimmetz** [comment]
I also opt sticking with "released" versions e.g. https://github.com/libyal/libvhdi/releases and not pulling from git HEAD.

**Comment by ryandesign** [comment]
Yes, certainly we use releases. I will advise the submitter of the ports that they were unnecessary and ask them to advise me on how to proceed with further packaging.

**Comment by xambroz** [comment]
Hello,
is there some drawback using those libraries (libuna, libcfile, libc*) shared and not static? 

I am trying to package new versions of libewf and libesedb for Fedora distribution (Rawhide). Fedora distribution has a rule that code/libraries, which are used by more than one project (libewf, libesedb, grr, plaso) should be shared instead of compiling them in static. Fedora has this rule for several reasons - like if some vulnerability is found in a code, fix is then controlled only one place. I am just trying to follow these rules to get ready to get the new vesions of libewt, libesedb and ultimately probably grr and plaso, dvfvs, plaso, log2timeline.

Back to the original libuna vs libcfile libcsystem

> Why do you want to package and distribute them all separately?

If I would like generate unatools from the same Fedora package as libuna it would create cyclic dependency to libcfile and libcsystem. 

See these are the dependencies as taken from the Makefile.am
libuna - depends on libcsystem,libsfile
        libcstring \
        libcerror \
        libcdatetime \
        libclocale \
        libcnotify \
        libcfile \
        libcsystem \

libcsystem - depends on libuna  
        libcstring \
        libcerror \
        libclocale \
        libcnotify \
        libuna \

libcfile       - depends on libuna
        libclocale \
        libcnotify \
        libuna \

The way I can deal with that in Fedora/RedHat , is to generate libuna separately as only a library, then the dependent libcfile,libcsystem packages and  then the unatools as a separate package.
For me as packager would be probably easier to have unatools distributed separately, but now that I found the workaround I can live with that.

Best regards
Michal Ambroz

**Comment by joachimmetz** [comment]
> is there some drawback using those libraries (libuna, libcfile, libc*) shared and not static? 
- more libraries and dependencies to maintain
- a bit more overhead in using shared libraries; loads, external calls
- more places where thread safety and locking needs to happen (more overhead)
- easier to get into version conflicts; especially with experimental code

> The way I can deal with that in Fedora/RedHat , is to generate libuna separately as only a library,
> then the dependent libcfile,libcsystem packages and then the unatools as a separate package.
> For me as packager would be probably easier to have unatools distributed separately, but now
> that I found the workaround I can live with that.

Even then I would urge not to separately package:
- libcstring
- libcsystem

These are just collections of common boilerplate code, no real functionality as a shared library.

This largely boils down to what is perceived as a separate library/code. There are a lot of projects out there that just include source files in the source directory instead of managing them as separate projects. Also ask yourself is the API "stable" enough to be considered as a separate shared library.

You do what ever you deem suitable for Fedora, you know my advice on the matter is not to do it.
