### ISSUE TITLE
circle dependence on libcfile

### ISSUE THREAD

**Issue by blshkv** [libyal/libuna#7]
I'm trying to install both libuna and libcfile into a system location and facing the problem.

Both libraries require each other to be present in the system before it can build

libcfile fails with the following:
```
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libuna   -march=native -O2 -pipe -Wall -c -o libcfile_system_string.lo libcfile_system_string.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libuna -march=native -O2 -pipe -Wall -c libcfile_support.c  -fPIC -DPIC -o .libs/libcfile_support.o
In file included from libcfile_support.c:44:0:
libcfile_libuna.h:29:34: fatal error: libuna_base16_stream.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile:555: libcfile_support.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libuna -march=native -O2 -pipe -Wall -c libcfile_system_string.c  -fPIC -DPIC -o .libs/libcfile_system_string.o
In file included from libcfile_system_string.c:31:0:
libcfile_libuna.h:29:34: fatal error: libuna_base16_stream.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile:555: libcfile_system_string.lo] Error 1
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libuna -march=native -O2 -pipe -Wall -c libcfile_file.c -o libcfile_file.o >/dev/null 2>&1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/libcfile-20170105_alpha/work/libcfile-20170105/libcfile'
make: *** [Makefile:577: all-recursive] Error 1
```

and libuna fails with the following:
```
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcfile    -march=native -O2 -pipe -Wall -c -o byte_size_string.o byte_size_string.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcfile    -march=native -O2 -pipe -Wall -c -o export_handle.o export_handle.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcfile    -march=native -O2 -pipe -Wall -c -o process_status.o process_status.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcfile    -march=native -O2 -pipe -Wall -c -o unabase.o unabase.c
In file included from export_handle.h:30:0,
                 from export_handle.c:29:
unatools_libcfile.h:31:34: fatal error: libcfile_definitions.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile:578: export_handle.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from export_handle.h:30:0,
                 from unabase.c:38:
unatools_libcfile.h:31:34: fatal error: libcfile_definitions.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile:578: unabase.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/libuna-20170112_alpha/work/libuna-20170112/unatools'
make: *** [Makefile:591: all-recursive] Error 1
```

Could you clarify the order please?

**Comment by joachimmetz** [comment]
libcfile is only used by the unatools. Can you clarify how you are building from source.

Also both libcfile and libuna are largely intended as development libraries to be used within other projects. There is typically little need to install them as shared libraries.

**Comment by blshkv** [comment]
I'm creating an ebuild for Gentoo Linux using autotools class. I have installed all required dependency in the same way so that this is the only issue left.

here is the detailed log:
https://gist.github.com/blshkv/a51205c90f7a876789dea0fbfce4cdd7

**Comment by joachimmetz** [comment]
Try using the source distribution package `libuna-alpha-20170112.tar.gz` instead of the github generated file `libuna-20170112.tar.gz`

**Comment by joachimmetz** [comment]
This is explained here: https://github.com/libyal/libuna/wiki/Building#read-first

**Comment by blshkv** [comment]
I think you are not getting it. I'm trying to build *without* local libcfile (or any other libraries).

**Comment by blshkv** [comment]
so ok, let me ask differently. So libuna requires libcfile because it is used by the unatools.

In turn, libcfile requires libuna. Can it be avoided?

**Comment by joachimmetz** [comment]
> I think you are not getting it. I'm trying to build without local libcfile (or any other libraries).

I do.

The answer is you need the local libraries in the source when building. You are using the development version which is not intended for the type of distribution you want to use it for. Use the source distribution version instead, it provides solutions for these issues.

> In turn, libcfile requires libuna. Can it be avoided?

no, use the source distribution version instead. Both libcfile and libuna are development libraries there is no need to install them as shared libraries on your system.

**Comment by blshkv** [comment]
hmm.. ok. So I switched to ```libuna-alpha-20170112.tar.gz``` and managed to compile and install as a shared library. Once done, I was able to compile libcpath and libcfile from "development" sources because all other libraries (libc*) are installed as shared in my system.

I guess it will break the wishes circle for now. But it would be good if these two would not rely on each other in future.

**Comment by joachimmetz** [comment]
> But it would be good if these two would not rely on each other in future.

This really depends on the perception/interpretation where a project boundary starts versus that of a system/distribution package.

1. the git (development) version is not intended to be redistribute-able where the source distribution package is
2. there is no need to install/deploy a development library as a shared library, it can introduce more issues than value, e.g. dealing with locking of shared resources, making update cycles more complex

**Comment by blshkv** [comment]
I would like to reopen this issue as we hit it again today by an accident.
Can I suggest to split out a common part which is required for both libraries to a separate module or merge these two into a single one?

You should admit that the current way is confusing and not common:
Library_A requires Library_B to compile
in the main time, 
Library_B requires Library_A to compile

That's the chicken and the Egg dilemma of the century which you seem managed to resolve!

**Comment by joachimmetz** [comment]
> You should admit that the current way is confusing and not common:

This is not true, it is not the library (libuna) that need the other library (libcfile). It's the tools (unatools).

This also only appears to be an issue for distro package maintainers that, against advice, want to deploy every libyal library as a shared object.

I'll consider deprecating the unatools, but this is a low priority on my (very long) todo list.

**Comment by joachimmetz** [comment]
Closing this issue in favor https://github.com/libyal/libuna/issues/11

**Comment by jengelh** [comment]
>against advice, want to deploy every libyal library as a shared object.

What is the advice, exactly? Can I find this in a file in the git trees? The wiki pages under https://github.com/libyal/libuna/wiki talk about shared/static only in terms of how to start the build but makes no judgement on whether it's a "good" or "bad" idea.

**Comment by joachimmetz** [comment]
> What is the advice, exactly? 

that is the advice I'm giving you

* until everything is stable there might be compatibility reasons, newer versions might not be compatible with a shared one
* also it adds more maintenance overhead that is not necessary
* it might create performance challenges due to thread locks
* the only support library you might want to consider using in a shared way is libbfio, if you have a specific need for it

**Comment by jengelh** [comment]
Asking for clarification on the fourth point. What if, as a program author, I want to make use of libcfile?
Are you opposing _the intent to use_? And/or, are you opposing that, as part of trying to use libcfile for $program, I let libcfile build as a shared library?

**Comment by joachimmetz** [comment]
The answer here is "it highly depends on the context"

> What if, as a program author, I want to make use of libcfile?

Are you or is this a hypothetical matter? If not can you give me some insight to (1) what you're planning to use it for? (2) what is the license of that software? (3) What platform are you planning to run it on? (4) What is your normal selection process for dependencies?

> Are you opposing the intent to use? And/or, are you opposing that, as part of trying to use libcfile for $program, I let libcfile build as a shared library?

There is nothing preventing you from using libcfile as a shared library. I have no idea what you're asking here, but it reads to me you're trying to lead this conversation in a certain direction.

**Comment by jengelh** [comment]
Running the build in the libuna directory produces, by default, a shared library. (and `make install` installs it.) Building libcfile then reuses, by default, the libuna from /usr. A software author who, by chance, selects and compiles his desired libyal components in the just the "right" order can end up with the "problematic" all-shared scenario without actively targeting distro packaging policies (the "all-shared doctrine"). What I am concerned about is that you give one advice but then the source code do something different.

On point (1), I have [a program](https://github.com/grommunio/gromox/blob/master/tools/pff2mt.cpp) that uses libpff. I am about to extend it to also use libolecf. If I follow the general advice and only build libpff, libolecf as shared, then the program will link to libpff.so.1 and libolecf.so.1, but there will be two copies of bfio, cdata, cerror, cfile, clocale, cnotify, cpath, csplit, cthreads and libuna in the process image, which wastes some amount of resources (current projection is about 3.37MB). It would get worse if and when I later start linking to libnk2 as well, because then I will be getting a third copy of bfio et al. Thus I find it very important to use shared libs at all stages, whenever that is technically possible. This is (2) AGPL-3.0 and for (3) Linux/BSD.

Regarding point (4), one development strategy is to reuse components that are already present in the process image. libpff pulls in libuna. If I can make use of una's base64 functions and throw out a different dependency that so far has done the base64 parts for me, that is considered a win. If libcfile has something of interest to me as well, then same thing. This loops back to the "what if I wanted to use libcfile" hypothesis from earlier.

**Comment by joachimmetz** [comment]
> A software author who, by chance, selects and compiles his desired libyal components in the just the "right" order can end up with the "problematic" all-shared scenario without actively targeting distro packaging policies (the "all-shared doctrine"). 

This applies to any software not build in the right order or with the right parameters. 

> Thus I find it very important to use shared libs at all stages, whenever that is technically possible.

We are talking in circles here, yes that is possible but NOT RECOMMENDED at this point. No argumentation is going to change that recommendation as I have told before NONE of these libraries are stable as clearly outlined in their README.

That should be part of your software selection process, to ensure that your dependency allows you to do what you want it to do.

> It would get worse if and when I later start linking to libnk2 as well, because then I will be getting a third copy of bfio et al. 

If the code would be directly in the projects we would NOT have this discussion, but you would still have the duplication. This sounds to me this is an argument for discussion sake. 

> If libcfile has something of interest to me as well, then same thing. This loops back to the "what if I wanted to use libcfile" hypothesis from earlier.

Again there is nothing stopping you from doing so, just NOT RECOMMENDED at this time.

**Comment by xambroz** [comment]
Please would you thing of some build conditional to the ./configure script which will allow to build with or without unatools?

This would solve the circle dependency as it would be possible to build a package with a bootstrap conditional, which will first build just the libuna, then libcfile, then libuna with the unatools

**Comment by jengelh** [comment]
--disable-tools exists.

Other than that, you can build with the bundled libcfile the first time around, and eventually circle back to libuna for a second round with the system libcfile.

That's enough options.
